# Import librarys

In [1]:
from keras.models import load_model
from keras.models import Model
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import tensorflow as tf
from sklearn.metrics import mean_squared_error
import keras
import yfinance as yf
from matplotlib.backends.backend_pdf import PdfPages
import pickle
import json

# read predicting sequence

In [2]:
def download_stock_data(stock_symbols, start_date, end_date, output_file):
    with open(output_file, 'w') as f:
        # write column headings
        f.write('Date,Open,High,Low,Close,Volume\n')
        
        #for symbol in stock_symbols:
            # load share data for the symbol (Share name) and the given time period
        stock_data = yf.download(symbol, start=start_date, end=end_date)
        stock_data = stock_data[['Open', 'High', 'Low', 'Close', 'Volume']]  # Auswahl der gewünschten Spalten
        stock_data.to_csv(f, header=False)  # Schreiben der Daten in die Datei

# load time sequence

In [3]:
# Enter symbols
stock_symbols = ['ALV.DE', 'DBK.DE', 'VOW3.DE', 'BMW.DE', 'ADS.DE', 'BEI.DE', 'DTE.SG', 'SAP.DE', '1COV.DE', 'BAS.DE', 'EOAN.DE', 'RWE.DE']
start_date = '2018-10-01'
end_date = '2018-12-31'

# load and store the data for every share
for symbol in stock_symbols:
    output_file = f'stock_data_{symbol}.csv'
    download_stock_data(symbol, start_date, end_date, output_file)

    # read CSV and select select the desired columns
    df = pd.read_csv(output_file, usecols=['Date', 'Open', 'High', 'Low', 'Close', 'Volume'])
    
    # Search CSV file for empty lines and remove them
    with open(output_file, 'r') as file:
        lines = file.readlines()

    # filter the empty lines
    lines = [line.strip() for line in lines if line.strip()]

    # Overwrite the file with the adjusted rows
    with open(output_file, 'w') as file:
        file.write('\n'.join(lines))

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed


In [4]:
# store the data frames for different symbols in the dictionary
dfPre = {}

for symbol in stock_symbols:
    # load CSV
    dfPre[symbol] = pd.read_csv(f'stock_data_{symbol}.csv')

    # Drop empty rows
    dfPre[symbol].dropna(inplace=True)

    # transform date to index
    dfPre[symbol].set_index('Date', inplace=True)

    # Check the number of rows
    num_rows = dfPre[symbol].shape[0]

    # If more than 60 rows, keep the last 60 rows
    if num_rows > 60:
        dfPre[symbol] = dfPre[symbol].tail(60)


In [5]:
# Check missing values
missing_values_beforePre = {symbol: dfPre[symbol].isnull().values.any() for symbol in stock_symbols}

# missing values are replaced with teh mean of the row before and after the actual row
for symbol in stock_symbols:
    for column in dfPre[symbol].columns:
        missing_valuesPre = dfPre[symbol][column].isnull()
        dfPre[symbol].loc[missing_valuesPre, column] = (dfPre[symbol][column].shift() + dfPre[symbol][column].shift(-1)) / 2

# Check if there are still any missing values 
missing_values_afterPre = {symbol: dfPre[symbol].isnull().values.any() for symbol in stock_symbols}

# Output of the missing values before and after the Treatment
for symbol in stock_symbols:
    print(f"Fehlende Werte vor der Behandlung für {symbol} gefunden:", missing_values_beforePre[symbol])
    print(f"Fehlende Werte nach der Behandlung für {symbol} gefunden:", missing_values_afterPre[symbol])

# Output of the length of the data frame for all symbols
for symbol in stock_symbols:
    print(f"Länge des Datensatzes für {symbol}:", len(dfPre[symbol]))


Fehlende Werte vor der Behandlung für ALV.DE gefunden: False
Fehlende Werte nach der Behandlung für ALV.DE gefunden: False
Fehlende Werte vor der Behandlung für DBK.DE gefunden: False
Fehlende Werte nach der Behandlung für DBK.DE gefunden: False
Fehlende Werte vor der Behandlung für VOW3.DE gefunden: False
Fehlende Werte nach der Behandlung für VOW3.DE gefunden: False
Fehlende Werte vor der Behandlung für BMW.DE gefunden: False
Fehlende Werte nach der Behandlung für BMW.DE gefunden: False
Fehlende Werte vor der Behandlung für ADS.DE gefunden: False
Fehlende Werte nach der Behandlung für ADS.DE gefunden: False
Fehlende Werte vor der Behandlung für BEI.DE gefunden: False
Fehlende Werte nach der Behandlung für BEI.DE gefunden: False
Fehlende Werte vor der Behandlung für DTE.SG gefunden: False
Fehlende Werte nach der Behandlung für DTE.SG gefunden: False
Fehlende Werte vor der Behandlung für SAP.DE gefunden: False
Fehlende Werte nach der Behandlung für SAP.DE gefunden: False
Fehlende Werte

# Data normalization prediction data

In [6]:
# load scaler
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
    
# min-max scale factors
min_value = scaler.data_min_
max_value = scaler.data_max_
# normalize the data for all symbols
nfPre = {}
nfPre_normalized = {}
for symbol in stock_symbols:
    # Copy the data fram and remove the column "Date" for every symbol
    nfPre[symbol] = dfPre[symbol].copy()
    
    # Remove the index name 
    nfPre[symbol].index.name = None

    # normalize the data for every symbol, except for the date (Index)
    nfPre_normalized[symbol] = scaler.transform(nfPre[symbol])

    # Create a new data frame with the normalized data and the original index for every symbol
    nfPre[symbol] = pd.DataFrame(nfPre_normalized[symbol], columns=nfPre[symbol].columns, index=nfPre[symbol].index)

    # Convert DataFrame to NumPy array for every symbol
    nfPre[symbol] = nfPre[symbol].to_numpy()
    

# Daten preparation

In [7]:
# Store X_pre for every symbol in the dictionary
X_pre_dict = {}

# Iterate over each symbol
for symbol in stock_symbols:
    
    nfPre_symbol = nfPre[symbol]
    
    # Define size for the current symbol
    nfPre_size_symbol = len(nfPre_symbol)
    
    # Add external dimension
    X_pre_symbol = np.expand_dims(nfPre_symbol[:nfPre_size_symbol], axis=0)
    
    # Transform to Tensor
    X_pre_symbol_tensor = tf.convert_to_tensor(X_pre_symbol, dtype=tf.float32)
    
    # Store in the dictionary
    X_pre_dict[symbol] = X_pre_symbol_tensor

# Model importieren

In [8]:
loaded_models = {}

for symbol in stock_symbols:
    # Load the stored model
    loaded_models[symbol] = load_model(f'Predict1Year_{symbol}.h5.keras')

In [9]:
print(loaded_models)

{'ALV.DE': <Sequential name=sequential, built=True>, 'DBK.DE': <Sequential name=sequential, built=True>, 'VOW3.DE': <Sequential name=sequential, built=True>, 'BMW.DE': <Sequential name=sequential, built=True>, 'ADS.DE': <Sequential name=sequential, built=True>, 'BEI.DE': <Sequential name=sequential, built=True>, 'DTE.SG': <Sequential name=sequential, built=True>, 'SAP.DE': <Sequential name=sequential, built=True>, '1COV.DE': <Sequential name=sequential, built=True>, 'BAS.DE': <Sequential name=sequential, built=True>, 'EOAN.DE': <Sequential name=sequential, built=True>, 'RWE.DE': <Sequential name=sequential, built=True>}


# Prediction for the unkonown sequence and transform back into monetary values

In [10]:
def prediction(symbol):
    # Predict the current share(symbol)
    predictions = loaded_models[symbol].predict(X_pre_dict[symbol])
    return predictions

In [11]:
# create dictionary to store the prediction for every symbol
predictions_dict = {}
predictions = {}

# Iterate over every symbol
for symbol in stock_symbols:

    # Prediction for the actual symbol
    predictions[symbol] = prediction(symbol)

    # Inverse transformation of the prediction
    predictions_original_scale_symbol = scaler.inverse_transform(predictions[symbol])

    # extract the prediction 20 days in the future
    prediction_20_days_ahead_symbol = predictions_original_scale_symbol[0][-2]

    # store the prediction for the current symbol
    predictions_dict[symbol] = {
        'prediction_20_days_ahead': prediction_20_days_ahead_symbol
    }

    # Output the values of the inverse transformation
    print(f"Zurücktransformierte Vorhersagen für {symbol}:")
    print(predictions_original_scale_symbol)
    print(prediction_20_days_ahead_symbol)
print(predictions_dict)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step
Zurücktransformierte Vorhersagen für ALV.DE:
[[4.8477291e+01 5.2120399e+01 4.6384171e+01 5.0421959e+01 6.6842765e+06]]
50.42196
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step
Zurücktransformierte Vorhersagen für DBK.DE:
[[1.5262897e+01 1.4950180e+01 1.4969557e+01 1.4869346e+01 1.0243163e+07]]
14.869346
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step
Zurücktransformierte Vorhersagen für VOW3.DE:
[[2.9207436e+01 2.8997992e+01 3.0793690e+01 2.9790468e+01 8.0602840e+06]]
29.790468
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step
Zurücktransformierte Vorhersagen für BMW.DE:
[[3.5927021e+01 3.5524639e+01 3.5756874e+01 3.9409405e+01 1.6885944e+07]]
39.409405
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
Zurücktransformierte Vorhersagen für ADS.DE:
[[ 8.080512e+01  8.132944e+01  6.626281e+01  7.139040e+01 -5.585156e+07]]
71.3904
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
Zurücktransformierte Vorhersagen für BEI.DE:
[[2.5599476e+01 2.6736332e+01 2.5497450e+01 2.3610800e+01 2.4783056e+07]]
23.6

# read test CSV from 2019

In [12]:
# time period
start_date = '2019-01-01'
end_date = '2019-12-31'
print(start_date)
print(end_date)

# load and store the data for every symbol
for symbol in stock_symbols:
    output_file = f'stock_data_{symbol}_2019.csv'
    download_stock_data(symbol, start_date, end_date, output_file)

    # read file
    with open(output_file, 'r') as file:
        lines = file.readlines()

    # filter the empty rows
    lines = [line.strip() for line in lines if line.strip()]

    # Overwrite the data with the cleaned rows
    with open(output_file, 'w') as file:
        file.write('\n'.join(lines))


[*********************100%%**********************]  1 of 1 completed

2019-01-01
2019-12-31



[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed


In [13]:
# load data for every symbol
for symbol in stock_symbols:
    # create name for the CSV
    csv_file = f'stock_data_{symbol}_2019.csv'
    
    # Load CSV
    df = pd.read_csv(csv_file)
    
    # Set date as index
    df.set_index('Date', inplace=True)
    
    # Select the desired column
    selected_columns = ['Open', 'High', 'Low', 'Close', 'Volume']
    df = df[selected_columns]
    
    # show data
    print(f"Daten für Symbol {symbol}:")
    print(df.head)


Daten für Symbol ALV.DE:
<bound method NDFrame.head of                   Open        High         Low       Close   Volume
Date                                                               
2019-01-02  175.500000  175.559998  171.960007  175.000000  1035404
2019-01-03  173.320007  175.220001  172.539993  173.160004   883973
2019-01-04  174.899994  178.020004  172.960007  177.360001  1234989
2019-01-07  178.240005  178.240005  174.600006  175.919998   914854
2019-01-08  176.240005  178.179993  175.440002  176.100006   989326
...                ...         ...         ...         ...      ...
2019-12-19  220.800003  221.000000  218.050003  218.949997  1319860
2019-12-20  218.899994  220.850006  218.699997  220.750000  3144001
2019-12-23  220.300003  220.850006  219.750000  220.600006   741986
2019-12-27  220.800003  221.550003  219.800003  220.600006   583074
2019-12-30  220.550003  220.750000  218.399994  218.399994   432548

[251 rows x 5 columns]>
Daten für Symbol DBK.DE:
<bound meth

# Compare predictions to actual share values

In [14]:
# list to store the mse (mean squared error) for every symbol
mse_list = []

# list to store the actual and predicted value for every symbol
all_actual_values = []
all_predicted_values = []

# Comparison of the actual and the predicted value for every symbol
for symbol in stock_symbols:
    # create name for the CSV
    csv_file = f'stock_data_{symbol}_2019.csv'
    
    # load CSV
    df = pd.read_csv(csv_file)
    
    # set date as index
    df.set_index('Date', inplace=True)
    
    # extract last row
    last_row = df.iloc[-1]
    
    # Extract the value from the "Close" column of the last row
    actual_close = last_row['Close']
    
    # Calculate the mean squared error (mse)
    mse = mean_squared_error([actual_close], [predictions_dict[symbol]['prediction_20_days_ahead']])
    
    # Add mse to the list
    mse_list.append(mse)
    
    # Create a data frame with just one row for the actual and the predicted "Close" value
    comparison_df = pd.DataFrame({'Actual': [actual_close], 'Predicted': predictions_dict[symbol]['prediction_20_days_ahead']}, index=[last_row.name])
    
    # Output of the comparison
    print(f"Vergleich für Symbol {symbol}:")
    print(comparison_df)
    print(f"MSE für Symbol {symbol}: {mse}")
    print("\n")
    
    # Add the actual and predicted value to the main list
    all_actual_values.append(actual_close)
    all_predicted_values.append(predictions_dict[symbol]['prediction_20_days_ahead'])
    
# calculate the mean squared error (mse) for all predictions
total_mse = mean_squared_error(all_actual_values, all_predicted_values)

# Output of the mse for all values
print(f"Gesamter Mean Squared Error für alle Vorhersagen: {total_mse}")

# Define custom encoder class to handle float32 values
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.float32):
            return float(obj)
        return super(NumpyEncoder, self).default(obj)

# Convert NumPy arrays in lists (if present)
predictions_dict_serializable = {symbol: predictions.tolist() if isinstance(predictions, np.ndarray) else predictions for symbol, predictions in predictions_dict.items()}
print(predictions_dict_serializable)
# extract predictions for the mean variance model
json_file = 'settings/predictions1Year_dict.json'

# Write array in JSON file
with open(json_file, 'w') as f:
    json.dump(predictions_dict_serializable, f, cls=NumpyEncoder)

Vergleich für Symbol ALV.DE:
                Actual  Predicted
2019-12-30  218.399994  50.421959
MSE für Symbol ALV.DE: 28216.620233438978


Vergleich für Symbol DBK.DE:
            Actual  Predicted
2019-12-30   6.917  14.869346
MSE für Symbol DBK.DE: 63.23980448753082


Vergleich für Symbol VOW3.DE:
                Actual  Predicted
2019-12-30  176.240005  29.790468
MSE für Symbol VOW3.DE: 21447.466968712342


Vergleich für Symbol BMW.DE:
               Actual  Predicted
2019-12-30  73.139999  39.409405
MSE für Symbol BMW.DE: 1137.7530144313496


Vergleich für Symbol ADS.DE:
                Actual  Predicted
2019-12-30  289.799988  71.390404
MSE für Symbol ADS.DE: 47702.74640288908


Vergleich für Symbol BEI.DE:
                Actual  Predicted
2019-12-30  106.650002    23.6108
MSE für Symbol BEI.DE: 6895.509025026873


Vergleich für Symbol DTE.SG:
            Actual  Predicted
2019-12-30   13.69  15.274905
MSE für Symbol DTE.SG: 2.5119258382219414


Vergleich für Symbol SAP.DE:
   